spring.application.name=japan-travel-planner

spring.datasource.url=jdbc:postgresql://127.0.0.1:55432/japan_planner
spring.datasource.username=planner
spring.datasource.password=planner
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=none
spring.flyway.enabled=true

app.cors.allowed-origin=http://localhost:5173